### ISSUE TITLE
REQUIRES DEPENDENCY

### ISSUE THREAD

**Issue by xAlphaOmega** [initOS/odoo-analyse#1]
Initially hit error because dependency wasn't installed but didn't call for it

pip3 install graphviz

**Comment by fkantelberg** [comment]
@xAlphaOmega Thank you for the feedback. We updated the readme and package accordingly. To use the package with the rendering you should install it with the extra graph. I hope this helps.
```
pip3 install "odoo-analyse[graph]"
```
