### ISSUE TITLE
Appear all modules

### ISSUE THREAD

**Issue by abdallamohamed-ever** [initOS/odoo-analyse#10]
Hello,
I run below command to custom addons only 
```
odoo_analyse -p CUSTOM_ADDONS_PATH --show-dependency
```
I found that if module does not depend on another custom module, graph does not appear it. Is there any way to appear standalone modules also not have dependency only?

**Comment by fkantelberg** [comment]
Hello @abdallamohamed-ever ,
can you please tell me the version you are using?

**Comment by abdallamohamed-ever** [comment]
@fkantelberg 
I use python version 3.8.10,  Odoo version 14 and odoo-analyse version 1.1.2

**Comment by ortlam** [comment]
Hello @abdallamohamed-ever 
by default single nodes do not appear in the rendered graph. You can change this behavior by setting the option `skip_lonely_node` to an empty string in the `analyse.cfg` in your work directory.

```
[odoo]
skip_lonely_node = 
```

Does this answer your question?

**Comment by abdallamohamed-ever** [comment]
@ortlam yes it work, Thanks
