### ISSUE TITLE
Missing encoding in file, but non ASCII character used. 

### ISSUE THREAD

**Issue by codingforfun** [initOS/odoo-analyse#6]
https://github.com/initOS/odoo-analyse/blob/21f29c7ef08b3e8717e4584cb8c74fd798ea42c1/src/odoo_analyse/utils.py#L1

produces: 
```
SyntaxError: Non-ASCII character '\xc2' in file .../env/lib/python2.7/site-packages/odoo_analyse/utils.py on line 1, but no encoding declared; 
```

**Comment by fkantelberg** [comment]
You are right python 2 requires a line that a file is using unicode. Because python 2 is EOL I would rather update the documentation to use python 3 instead and install using pip3. Using python2 as interpreter might cause problems if you analyse python 3.6+ code anyways.
