### ISSUE TITLE
[Wishlist] ability to print output to terminal instead of in JSON file

### ISSUE THREAD

**Issue by Yenthe666** [initOS/odoo-analyse#8]
First of all, thanks for the cool work :)
Right now if you do this:
```
sudo odoo_analyse --path /tmp/auto_backup/14.0/auto_backup/ -s test.json
```
It will create a file on your disk and store it. However, in some cases you'd like this to happen in the terminal so you can use third party libraries to capture the terminal output in memory. It would be cool if we could do this:
```
sudo odoo_analyse --path /tmp/auto_backup/14.0/auto_backup/ --output-format=json
```
or
```
sudo odoo_analyse --path /tmp/auto_backup/14.0/auto_backup/ --f=json
```

Much like the `pylint` library works:
> -f <format>, --output-format=<format>
                        Set the output format. Available formats are text,
                        parseable, colorized, json and msvs (visual studio).
                        You can also give a reporter class, e.g.
                        mypackage.mymodule.MyReporterClass. [current: text]

**Comment by fkantelberg** [comment]
@Yenthe666 Thanks for the request.

Yes we can use stdout and stdin with `-s` and `-l`. I guess we would to the same as `--analyse -` which is outputting to stdout. But we might be a bit limitted with the output format because we don't want to loose information and some representations are hard to load again because these arguments are mostly a cache.

Have you checked `--analyse` and the output? Could be this helpful for your later processing too?

**Comment by Yenthe666** [comment]
Thanks for the feedback @fkantelberg :)
I did check the output (in the JSON file) and it has some really cool potential options to be honest. It would be great to have it available in `stdout` etc so you can use some `subprocess` to get the content out directly.

**Comment by fkantelberg** [comment]
@Yenthe666 This 2f9611c443c4c89408e3a1d5f88fa00fb0bb333d should add the requested feature and I redirected the logging to stderr to avoid problems. You can install the newest version 1.1.1.

If you use it in a python script you might favor the usage as package:
```
>>> from odoo_analyse import Odoo
>>> odoo = Odoo.from_path(".")
>>> list(odoo)
['auth_session_timeout', 'auth_ldaps', ...]
>>> odoo["auth_session_timeout"].models
{'ir.http': <Model: ir.http>, 'ir.config_parameter': <Model: ir.config_parameter>, 'res.users': <Model: res.users>}
>>> odoo["auth_session_timeout"].manifest
{...}
```

**Comment by Yenthe666** [comment]
Cool thanks! This works like a charm :)
A sample:
```
sudo odoo_analyse --path /tmp/auto_backup/14.0/auto_backup/ -s -
```
I also added a little bit more documentation at https://github.com/initOS/odoo-analyse/pull/9 :)
